export const initialPrompts = [
  {
    id: "1",
    slug: "generate-technical-blog-ideas",
    title: "Generate technical blog ideas",
    description: "Generate engaging blog post ideas tailored for a tech audience and software developers.",
    prompt: "Act as a content strategist for a tech blog. Generate 10 engaging and SEO-friendly blog post ideas that would appeal to software developers. The topics should be relevant to current trends in technology, programming languages, tools, or best practices. For each idea, provide a catchy title and a brief description of what the post would cover.",
    category: "writing",
    tags: ["blog", "content", "tech"],
    author: "Admin",
    createdAt: "2024-01-01",
    upvotes: 124
  },
  {
    id: "2",
    slug: "react-component-boilerplate",
    title: "React Component Boilerplate",
    description: "Instantly generate a modern React functional component with Tailwind and PropTypes.",
    prompt: "Write a React functional component named [ComponentName]. It should use Tailwind CSS for styling, include basic prop types, and have a properly structured return statement with semantic HTML. Include a default export.",
    category: "coding",
    tags: ["react", "frontend", "boilerplate"],
    author: "DevGuru",
    createdAt: "2024-01-05",
    upvotes: 89
  },
  {
    id: "3",
    slug: "seo-optimized-meta-description",
    title: "SEO Optimized Meta Description",
    description: "Create highly converting meta descriptions for any landing page.",
    prompt: "Write 3 variations of an SEO-optimized meta description for a webpage about [Topic]. Keep them under 160 characters, include a clear call to action, and make them highly clickable.",
    category: "marketing",
    tags: ["seo", "marketing", "copywriting"],
    author: "SEO_Master",
    createdAt: "2024-01-10",
    upvotes: 256
  },
  {
    id: "4",
    slug: "sql-query-optimizer",
    title: "SQL Query Optimizer",
    description: "Find bottlenecks and optimize complex SQL queries.",
    prompt: "Act as a Senior Database Administrator. Analyze the following SQL query for performance bottlenecks and rewrite it to be more efficient. Explain the changes you made and why they improve performance: \n\n[Insert SQL Query Here]",
    category: "data",
    tags: ["sql", "database", "optimization"],
    author: "DataNinja",
    createdAt: "2024-02-15",
    upvotes: 67
  },
  {
    id: "5",
    slug: "polite-rejection-email",
    title: "Polite Rejection Email",
    description: "Say no to a candidate or vendor gracefully.",
    prompt: "Write a polite and professional rejection email to a [candidate/vendor] who applied for [Position/Service]. Thank them for their time, provide a brief but generic reason for going in another direction, and wish them well.",
    category: "writing",
    tags: ["email", "professional", "hr"],
    author: "HR_Pro",
    createdAt: "2024-03-02",
    upvotes: 42
  },
  {
    id: "6",
    slug: "regex-builder",
    title: "Regex Builder",
    description: "Easily generate complex Regular Expressions with explanations.",
    prompt: "Act as a Regex Expert. Create a regular expression that matches [Describe what you want to match]. Provide the regex in a code block, and then explain step-by-step how each part of the expression works. Also provide 3 passing test cases and 3 failing test cases.",
    category: "coding",
    tags: ["regex", "tools", "development"],
    author: "CodeWizard",
    createdAt: "2024-03-10",
    upvotes: 112
  },
  {
    id: "7",
    slug: "cover-letter-generator",
    title: "Cover Letter Generator",
    description: "Create a tailored cover letter based on a job description.",
    prompt: "Write a professional and compelling cover letter for the role of [Job Title] at [Company Name]. Here is my resume: [Paste Resume] and here is the job description: [Paste Job Description]. Ensure the tone is enthusiastic and highlights my most relevant skills.",
    category: "writing",
    tags: ["career", "cover letter", "professional"],
    author: "CareerCoach",
    createdAt: "2024-03-12",
    upvotes: 340
  },
  {
    id: "8",
    slug: "social-media-content-calendar",
    title: "Social Media Content Calendar",
    description: "Generate a month's worth of social media post ideas.",
    prompt: "Create a 4-week social media content calendar for a [Business Type] targeting [Target Audience]. Include 3 posts per week across platforms like Instagram, LinkedIn, and Twitter. Format the output as a table with columns for Week, Day, Platform, Content Theme, and a short caption draft.",
    category: "marketing",
    tags: ["social media", "planning", "content"],
    author: "SocialSavvy",
    createdAt: "2024-03-15",
    upvotes: 215
  },
  {
    id: "9",
    slug: "excel-formula-expert",
    title: "Excel Formula Expert",
    description: "Solve complex Excel data manipulation problems.",
    prompt: "Act as an Advanced Excel user. I need a formula to achieve the following: [Describe your goal, e.g., sum values in column B if column A matches a specific date]. Explain how the formula works and provide any alternative approaches using modern Excel functions like XLOOKUP or FILTER.",
    category: "data",
    tags: ["excel", "spreadsheet", "formulas"],
    author: "SheetMaster",
    createdAt: "2024-03-18",
    upvotes: 198
  },
  {
    id: "10",
    slug: "meeting-agenda-creator",
    title: "Meeting Agenda Creator",
    description: "Design structured and time-boxed meeting agendas.",
    prompt: "Create a highly structured, time-boxed meeting agenda for a [Duration, e.g., 45-minute] meeting about [Meeting Topic]. The goal of this meeting is [Meeting Goal]. Include specific time slots for each agenda item, designate a facilitator, and include a section for action items.",
    category: "business",
    tags: ["productivity", "meetings", "management"],
    author: "BizOps",
    createdAt: "2024-03-20",
    upvotes: 85
  },
  {
    id: "11",
    slug: "character-backstory-generator",
    title: "Character Backstory Generator",
    description: "Flesh out detailed backstories for fiction or RPG characters.",
    prompt: "Write a compelling backstory for a character named [Character Name], who is a [Class/Profession] in a [Genre/Setting] world. Include details about their childhood, their greatest fear, their main motivation, and a secret they are hiding from their allies.",
    category: "creative",
    tags: ["writing", "rpg", "character design"],
    author: "StoryTeller",
    createdAt: "2024-03-22",
    upvotes: 156
  },
  {
    id: "12",
    slug: "git-command-explainer",
    title: "Git Command Explainer",
    description: "Understand complex Git commands and resolve conflicts.",
    prompt: "I am stuck in a Git situation: [Describe the problem, e.g., I accidentally committed to master instead of a branch]. Explain step-by-step how I can fix this issue safely without losing my work. Provide the exact terminal commands I need to run.",
    category: "coding",
    tags: ["git", "version control", "debugging"],
    author: "RepoMaster",
    createdAt: "2024-03-25",
    upvotes: 310
  },
  {
    id: "13",
    slug: "product-description-writer",
    title: "Product Description Writer",
    description: "Write e-commerce product descriptions that convert.",
    prompt: "Write a persuasive and sensory-rich e-commerce product description for [Product Name]. The product features are [List Features]. The target audience is [Target Audience]. Focus on the benefits of the product, not just the features, and end with a strong call to action.",
    category: "marketing",
    tags: ["ecommerce", "copywriting", "sales"],
    author: "EcomNinja",
    createdAt: "2024-03-28",
    upvotes: 142
  },
  {
    id: "14",
    slug: "swot-analysis-generator",
    title: "SWOT Analysis Generator",
    description: "Conduct a rapid SWOT analysis for any business idea.",
    prompt: "Conduct a comprehensive SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for a company that does [Describe the business model/idea]. Present the analysis in a clear, structured bulleted list and provide a concluding summary of their strategic position.",
    category: "business",
    tags: ["strategy", "planning", "analysis"],
    author: "ConsultantAI",
    createdAt: "2024-04-01",
    upvotes: 204
  },
  {
    id: "15",
    slug: "midjourney-portrait-prompt",
    title: "Midjourney Portrait Prompt",
    description: "Generate highly detailed prompts for AI image generators.",
    prompt: "Write a highly detailed prompt for Midjourney v6 to generate a photorealistic portrait of [Subject Description]. Include specific keywords for lighting (e.g., cinematic, golden hour), camera angle, lens focal length, atmosphere, and artistic style. Format it as a single comma-separated paragraph.",
    category: "creative",
    tags: ["ai art", "midjourney", "prompts"],
    author: "PixelArtist",
    createdAt: "2024-04-05",
    upvotes: 275
  },
  {
    id: "16",
    slug: "python-data-analysis-script",
    title: "Python Data Analysis Script",
    description: "Generate boilerplate Pandas code for data tasks.",
    prompt: "Write a Python script using Pandas to perform the following analysis: [Describe task, e.g., Load a CSV, handle missing values, group by 'category' and calculate the mean of 'sales']. Include comments explaining each step and ensure best practices for performance.",
    category: "data",
    tags: ["python", "pandas", "data science"],
    author: "DataSci",
    createdAt: "2024-04-08",
    upvotes: 188
  },
  {
    id: "17",
    slug: "email-newsletter-draft",
    title: "Email Newsletter Draft",
    description: "Draft engaging weekly newsletters for your subscribers.",
    prompt: "Draft a weekly email newsletter for an audience interested in [Niche/Topic]. Include an engaging subject line, a friendly intro, 3 main sections highlighting [Key Point 1, Key Point 2, Key Point 3], and a sign-off. Keep the tone [Tone, e.g., casual and informative].",
    category: "marketing",
    tags: ["email", "newsletter", "engagement"],
    author: "InboxPro",
    createdAt: "2024-04-10",
    upvotes: 95
  },
  {
    id: "18",
    slug: "css-grid-layout-generator",
    title: "CSS Grid Layout Generator",
    description: "Easily generate complex CSS Grid templates.",
    prompt: "Write the CSS and HTML for a responsive grid layout that looks like this: [Describe layout, e.g., a header, a sidebar on the left, a main content area, and a footer]. Use CSS Grid, make it responsive so the sidebar stacks on mobile, and provide clean, modern styling.",
    category: "coding",
    tags: ["css", "frontend", "design"],
    author: "StyleGuru",
    createdAt: "2024-04-12",
    upvotes: 134
  },
  {
    id: "19",
    slug: "pitch-deck-outline",
    title: "Pitch Deck Outline",
    description: "Structure a 10-slide pitch deck for investors.",
    prompt: "Create a 10-slide pitch deck outline for a startup in the [Industry] space doing [Value Proposition]. For each slide, provide the title, the key message that needs to be communicated, and suggestions for the visual elements to include on that slide.",
    category: "business",
    tags: ["startup", "fundraising", "pitch"],
    author: "FounderBot",
    createdAt: "2024-04-15",
    upvotes: 177
  },
  {
    id: "20",
    slug: "tone-of-voice-transformer",
    title: "Tone of Voice Transformer",
    description: "Rewrite text to match a specific tone or audience.",
    prompt: "Rewrite the following text to sound more [Desired Tone, e.g., authoritative, humorous, empathetic, professional]. Ensure the core message remains the same but adapt the vocabulary and sentence structure. Text to rewrite: [Paste Text Here]",
    category: "writing",
    tags: ["editing", "tone", "copywriting"],
    author: "Wordsmith",
    createdAt: "2024-04-18",
    upvotes: 211
  },
  {
    id: "21",
    slug: "dd-campaign-hook",
    title: "D&D Campaign Hook",
    description: "Generate engaging starting scenarios for tabletop RPGs.",
    prompt: "Create 3 unique and engaging campaign hooks for a Dungeons & Dragons campaign set in a [Setting Description, e.g., floating steampunk city]. Each hook should include a call to action, a hidden twist, and a primary NPC the players will interact with.",
    category: "creative",
    tags: ["gaming", "rpg", "worldbuilding"],
    author: "DungeonMaster",
    createdAt: "2024-04-20",
    upvotes: 145
  },
  {
    id: "22",
    slug: "pandas-dataframe-operations",
    title: "Pandas DataFrame Operations",
    description: "Quickly get solutions for Pandas dataframe manipulations.",
    prompt: "I have a Pandas DataFrame structured like this: [Describe columns and data types]. I need to achieve the following transformation: [Describe desired output]. Please provide the most efficient Python/Pandas code to do this without using loops.",
    category: "data",
    tags: ["python", "pandas", "data engineering"],
    author: "DataNinja",
    createdAt: "2024-04-22",
    upvotes: 110
  },
  {
    id: "23",
    slug: "okr-generator",
    title: "OKR Generator",
    description: "Create Objectives and Key Results for a team.",
    prompt: "Act as an executive coach. Generate 3 Objectives and 3 corresponding measurable Key Results (OKRs) for a [Department/Team, e.g., Customer Success Team] aiming to [Primary Goal, e.g., increase customer retention and upselling].",
    category: "business",
    tags: ["management", "goals", "okrs"],
    author: "LeaderBot",
    createdAt: "2024-04-25",
    upvotes: 92
  },
  {
    id: "24",
    slug: "dockerfile-creator",
    title: "Dockerfile Creator",
    description: "Generate a production-ready Dockerfile.",
    prompt: "Write a production-ready Dockerfile for a [Tech Stack, e.g., Node.js Express] application. Use a lightweight base image, implement multi-stage builds if appropriate, set up a non-root user for security, and expose port [Port Number]. Include comments explaining your choices.",
    category: "coding",
    tags: ["devops", "docker", "infrastructure"],
    author: "DevOpsPro",
    createdAt: "2024-04-28",
    upvotes: 165
  },
  {
    id: "25",
    slug: "story-outline-generator",
    title: "Story Outline Generator",
    description: "Use the Hero's Journey to outline a story.",
    prompt: "Outline a story using the Hero's Journey framework about a [Protagonist Description] who must [Core Conflict/Goal]. Provide a brief paragraph for each of the 12 stages of the Hero's Journey, ensuring logical progression and character growth.",
    category: "creative",
    tags: ["writing", "fiction", "storytelling"],
    author: "AuthorAI",
    createdAt: "2024-05-01",
    upvotes: 230
  },
  {
    id: "26",
    slug: "youtube-video-hook",
    title: "YouTube Video Hook",
    description: "Write engaging hooks for the first 15 seconds of a video.",
    prompt: "Write 5 highly engaging script hooks (for the first 10-15 seconds) for a YouTube video titled '[Video Title]'. The hooks should instantly grab the viewer's attention, create curiosity, and give them a reason to watch the rest of the video.",
    category: "marketing",
    tags: ["youtube", "video", "engagement"],
    author: "CreatorTools",
    createdAt: "2024-05-03",
    upvotes: 180
  },
  {
    id: "27",
    slug: "sql-schema-generator",
    title: "SQL Schema Generator",
    description: "Design relational database schemas quickly.",
    prompt: "Design a relational database schema for a [Type of Application, e.g., food delivery app]. Provide the SQL CREATE TABLE statements for the core entities (at least 4 tables). Ensure proper primary keys, foreign keys, data types, and timestamps. Briefly explain the relationships.",
    category: "data",
    tags: ["sql", "database", "architecture"],
    author: "DB_Admin",
    createdAt: "2024-05-06",
    upvotes: 155
  },
  {
    id: "28",
    slug: "brand-name-ideas",
    title: "Brand Name Ideas",
    description: "Brainstorm creative and available brand names.",
    prompt: "Brainstorm 20 creative, short, and memorable brand name ideas for a new company that does [Describe Company]. Group them by category: 1) Descriptive, 2) Abstract/Made-up, 3) Metaphorical, and 4) Portmanteaus.",
    category: "creative",
    tags: ["branding", "startup", "brainstorming"],
    author: "BrandGenius",
    createdAt: "2024-05-08",
    upvotes: 202
  },
  {
    id: "29",
    slug: "interview-questions-generator",
    title: "Interview Questions Generator",
    description: "Prepare tailored interview questions for candidates.",
    prompt: "Generate a list of 10 interview questions to evaluate a candidate for a [Job Role] position. Include 3 technical questions, 3 behavioral/situational questions, 3 cultural fit questions, and 1 creative problem-solving question. Provide what to look for in a good answer for each.",
    category: "business",
    tags: ["hr", "hiring", "interviews"],
    author: "TalentAcq",
    createdAt: "2024-05-10",
    upvotes: 118
  },
  {
    id: "30",
    slug: "react-hook-boilerplate",
    title: "React Hook Boilerplate",
    description: "Generate custom React hooks with TypeScript.",
    prompt: "Write a custom React hook named `use[HookName]` that handles [Describe what the hook should do, e.g., fetching data, tracking window size]. Write it in TypeScript, include proper type definitions, error handling, and a simple usage example in a component.",
    category: "coding",
    tags: ["react", "frontend", "hooks"],
    author: "ReactNinja",
    createdAt: "2024-05-12",
    upvotes: 288
  },
  {
    id: "31",
    slug: "uxui-copywriter",
    title: "UX/UI Copywriter",
    description: "Write concise and clear microcopy for interfaces.",
    prompt: "Act as a UX writer. I need microcopy for a [Type of UI element, e.g., 404 error page, success toast, empty state]. The context is [Describe the situation]. Provide 3 different variations of the copy: 1) Straightforward and clear, 2) Friendly and encouraging, 3) Slightly humorous.",
    category: "writing",
    tags: ["ux", "design", "microcopy"],
    author: "DesignWords",
    createdAt: "2024-05-15",
    upvotes: 175
  }
];